name: 'publish'
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: install dependenies
        run: |
          export ELECTRON_SKIP_BINARY_DOWNLOAD=1
          yarn install

      - name: build
        run: yarn build

      - name: zip
        run: |
          sudo apt install zip -y
          cd ./dist/
          zip -r ../LLOneBot.zip ./*

      - name: publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'LLOneBot.zip'
          draft: true
          token: ${{ secrets.RELEASE_TOKEN }}
